services:
  postgres:
    image: postgres:17
    container_name: url_shortener_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: url_shortener
      POSTGRES_USER: url_admin
      POSTGRES_PASSWORD: url_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: